In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np


In [6]:
food=np.array(["pakora",'samosa',"raita"])

In [7]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.empty(2)

array([8.61177273e-74, 2.59651195e+08])

In [9]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [10]:
price=np.array([5,5,5])
price

array([5, 5, 5])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(2,20,3)
#for intervels of 3

array([ 2,  5,  8, 11, 14, 17])

In [14]:
#table of 5
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [15]:
np.linspace(1,10, num=4)
#agr ap  ny is function ko use krky aik argument bnana hy  means ky 1 sy ly kr 10 tk jo difference
#ata hy wo 4 num ky difference sy  aye


array([ 1.,  4.,  7., 10.])

In [16]:
#specify your data type
np.ones(5,dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [17]:
np.ones(50,dtype=np.float64)

#integer or float ponit numbers ko use krty hen
#for getting missing values
#for  building own data set
#for out of the stock values ko  bhi find kr skty hen

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#Array function


In [18]:
a=np.array([10,12,15,32,23,43,23,344,32,1012])
a

array([  10,   12,   15,   32,   23,   43,   23,  344,   32, 1012])

In [19]:
a.sort()
a

array([  10,   12,   15,   23,   23,   32,   32,   43,  344, 1012])

In [20]:
b=np.array([1,23,45,54,23,23,233,2332,233])
b


array([   1,   23,   45,   54,   23,   23,  233, 2332,  233])

In [21]:
c=np.concatenate((a,b))
c

array([  10,   12,   15,   23,   23,   32,   32,   43,  344, 1012,    1,
         23,   45,   54,   23,   23,  233, 2332,  233])

In [22]:
c.sort()
c

array([   1,   10,   12,   15,   23,   23,   23,   23,   23,   32,   32,
         43,   45,   54,  233,  233,  344, 1012, 2332])

#  2_D arrays

In [23]:
a=np.array([[1,2,3,45,45],[3,3,23,32,33]])
a

array([[ 1,  2,  3, 45, 45],
       [ 3,  3, 23, 32, 33]])

In [24]:
b=np.array([[6,7,8,9,10],[5,6,7,8,9]])
b

array([[ 6,  7,  8,  9, 10],
       [ 5,  6,  7,  8,  9]])

In [25]:
c=np.concatenate((a,b),axis=0)
c

array([[ 1,  2,  3, 45, 45],
       [ 3,  3, 23, 32, 33],
       [ 6,  7,  8,  9, 10],
       [ 5,  6,  7,  8,  9]])

In [26]:
c=np.concatenate((a,b),axis=1)
c

array([[ 1,  2,  3, 45, 45,  6,  7,  8,  9, 10],
       [ 3,  3, 23, 32, 33,  5,  6,  7,  8,  9]])

In [27]:

d=np.array([[ 1,  2,  3, 45, 45],
            
       [ 3,  3, 23, 32, 33],
       [ 6,  7,  8,  9, 10],
            
       [ 5,  6,  7,  8,  9]])
d

array([[ 1,  2,  3, 45, 45],
       [ 3,  3, 23, 32, 33],
       [ 6,  7,  8,  9, 10],
       [ 5,  6,  7,  8,  9]])

In [28]:
#to find the num of dimension
d.ndim

2

In [29]:
b=np.array([[5,5,6,5],
          [4,4,3,4,],
          [32,23,23,1]])
b

array([[ 5,  5,  6,  5],
       [ 4,  4,  3,  4],
       [32, 23, 23,  1]])

In [30]:
b.ndim

2

In [31]:
b=np.array([[[5,5,6,5]],
          [[4,4,3,4,]],
          [[32,23,23,1]]])
b

array([[[ 5,  5,  6,  5]],

       [[ 4,  4,  3,  4]],

       [[32, 23, 23,  1]]])

In [32]:
b.ndim

3

In [33]:
b.size

12

In [34]:
b.shape
#dimension+rows+values

(3, 1, 4)

In [35]:
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
a=a.reshape(3,3) # 3*3=9

b

array([[[ 5,  5,  6,  5]],

       [[ 4,  4,  3,  4]],

       [[32, 23, 23,  1]]])

# convert 1D  into 2D

In [37]:
a=np.array([1,2,3,4,5,6,5,5,43,])
a

array([ 1,  2,  3,  4,  5,  6,  5,  5, 43])

In [38]:
a.shape


(9,)

In [39]:
b=a[np.newaxis, :]
b
#rowswise conversion

array([[ 1,  2,  3,  4,  5,  6,  5,  5, 43]])

In [40]:
b.shape


(1, 9)

In [41]:
b=a[:,np.newaxis]
b
#column wise conversion

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 5],
       [ 5],
       [43]])

In [42]:
#indexng
a

array([ 1,  2,  3,  4,  5,  6,  5,  5, 43])

In [43]:
a[2:5]

array([3, 4, 5])

In [44]:
#repitation of array
a

array([ 1,  2,  3,  4,  5,  6,  5,  5, 43])

In [45]:
a*6


array([  6,  12,  18,  24,  30,  36,  30,  30, 258])

In [46]:
a

array([ 1,  2,  3,  4,  5,  6,  5,  5, 43])

In [47]:
a+6


array([ 7,  8,  9, 10, 11, 12, 11, 11, 49])

In [48]:
a.sum()

74

In [49]:
a.mean()

8.222222222222221